### PR TITLE
SilverStripe 4 compatibility

### PR DESCRIPTION
**Pull request by anselmdk**
This will break backward compatibility with SilverStripe 3, so I suggest you make a final release, and an `ss3` branch for SilverStripe 3 support, and merge this to master.

### CODE REVIEW

**Comment by anselmdk** [comment]
This gives an issue with https://github.com/froog/SilverGraph/issues/6 though. Bummer. I'd be happy to post a bounty if anyone's interested in getting this merged, and fixing that issue.

**Comment by froog** [comment]
Hi @anselmdk, I'll take a look at this and see what I can find

**Comment by ntd** [comment]
@anselmdk No disrespect intended, but I don't know how to integrate a pull request (and even if it is possible) so I just opened a new one that includes your patch (see #20).

**Comment by anselmdk** [comment]
Thats, fine, it's been a long time. I'm closing it then.

**Pull request closed without merging**
